databases:
  - name: todo-db
    databaseName: todo-db
    user: postgres

services:
  - type: web
    name: todo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4