databases:
  - name: tododb
    databaseName: tododb_gzai
    user: tododb_gzai_user

services:
  - type: web
    name: todo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tododb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4